### ISSUE TITLE
Please update about "WillPopScope" deprecated.

### ISSUE THREAD

**Issue by etgkqo** [quentinleguennec/flutter-progress-loader-overlay#1]
I am using "WillPopScopeLoader". 
Please update me on the widget as flutter has announced that it will not use "WillPopScope" in the future.

**Comment by quentinleguennec** [comment]
@etgkqo Done, the new version 4.0.0 has a new implementation called `PopScopeLoader` to replace `WillPopScopeLoader`.

If you get a chance to test it, can you let me know if it works as expected? Thanks
